services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest #ghcr.io/hotio/radarr
    user: 0:666
    networks:
      - proxy
    container_name: radarr
    hostname: radarr
    dns: 
      - 172.22.20.1
      - 8.8.8.8
    volumes:
      - ./config:/config
      - /dev/fuse:/dev/fuse
      - /media:/media
      - /downloads:/downloads
      - /downloads:/download
    environment:
      - APP_GROUP=Requests
      - APP_LOGO=https://static-00.iconduck.com/assets.00/radarr-icon-231x256-t45eodqo.png
      - VIRTUAL_HOST=radarr.admin.pknw1.co.uk
      - VIRTUAL_PORT=7878
      - PUID=666
      - PGID=666

networks:
  proxy:
    external: true

